server:
  servlet:
    context-path: /mybatis
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_mybatis_demo?useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: abc123456
  thymeleaf:
    prefix: "classpath:/templates/"
    suffix: ".html"
    servlet:
      content-type: text/html